app:
  greeting: Hello World from config server
  description: Welcome to ${app.nem}}
  list:
    values: one,two,three

db:
  connection: config-server-connection-string-here-satnam
  host: 127.0.0.0
  port: 1200

management:
  endpoints:
    web:
      exposure:
        include: "*"


